MATRIX_W = 78
MATRIX_H = 20
MATRIX_Z = 10
SECTOR_W = MATRIX_W
SECTOR_H = MATRIX_H
SECTOR_Z = MATRIX_Z
COLOR_WK = 0
COLOR_RK = 1
COLOR_GK = 2
COLOR_YK = 3
COLOR_BK = 4
COLOR_MK = 5
COLOR_CK = 6
COLOR_KW = 7
STYLE_NORMAL = 'NORMAL'
STYLE_DIM = 'DIM'
STYLE_BOLD = 'BOLD'
STYLE_STANDOUT = 'STANDOUT'
STYLE_REVERSE = 'REVERSE'
STYLE_UNDERLINE = 'UNDERLINE'
STYLE_BLINK = 'BLINK'
STAR_CLASSES = ['O', 'B', 'A', 'F', 'G', 'K', 'M', 'BKH']
STAR_COLORS = {
    'O': COLOR_BK,
    'B': COLOR_CK,
    'A': COLOR_WK,
    'F': COLOR_WK,
    'G': COLOR_YK,
    'K': COLOR_MK,
    'M': COLOR_RK,
    'BKH': COLOR_KW
}
MAX_STARS_IN_SYS = 10
